spring:
  application:
    name: API-GATEWAY
cloud:
  gateway:
    routes:
      - id: ORDER-SERVICE
        uri: lb://ORDER-SERVICE
        predicates:
          - Path=/order/**
        filters:
          - StripPrefix=1
      - id: PAYMENT-SERVICE
        uri: lb://PAYMENT-SERVICE
        predicates:
          - Path=/payment/**
        filters:
          - StripPrefix=1




eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8085
